security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
        MY\EntityBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
              chain:
                  providers: [fos_userbundle, fos_facebook_provider]
        main:
            entity: { class: MYEntityBundle:User }

        fos_userbundle:
            id: fos_user.user_provider.username
        fos_facebook_provider:
            id: facebook_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|bitbucket)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        facebook_area:
            pattern:    ^/security/facebook
            context: shared
            fos_facebook:
                provider: fos_facebook_provider
                check_path: _security_facebook_check
                login_path: _login
                redirect_to_facebook_login: false
            logout:
                path:   _logout

        secured_area:
            pattern:    ^/.*
            context: shared
            form_login:
                check_path: _security_check
                login_path: _login
            logout:
                path:   _logout
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
